// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXQrAe5rOBITUlEx2vzQd-_Crj-i5Woo',
    appId: '1:480737324374:android:e8376d8782dedd2fa8faf7',
    messagingSenderId: '480737324374',
    projectId: 'flutter-full-new-36472',
    storageBucket: 'flutter-full-new-36472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB75dFuWlbhvJ1lUVi14y9-KtNgcoyyxX8',
    appId: '1:480737324374:ios:c13f64b550c93121a8faf7',
    messagingSenderId: '480737324374',
    projectId: 'flutter-full-new-36472',
    storageBucket: 'flutter-full-new-36472.appspot.com',
    iosBundleId: 'com.example.fullNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB75dFuWlbhvJ1lUVi14y9-KtNgcoyyxX8',
    appId: '1:480737324374:ios:57027c5e5422666fa8faf7',
    messagingSenderId: '480737324374',
    projectId: 'flutter-full-new-36472',
    storageBucket: 'flutter-full-new-36472.appspot.com',
    iosBundleId: 'com.example.fullNewsApp.RunnerTests',
  );
}
